name: Central Maven Build & Deploy

on:
  workflow_call:
    inputs:
      artifact_id:
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug â€“ print received input
        run: |
          echo "================ DEBUG INFO ================"
          echo "ðŸ‘‰ Received artifact_id input: '${{ inputs.artifact_id }}'"
          echo "============================================"

      - name: Build
        run: |
          if [ "${{ inputs.artifact_id }}" = "all" ]; then
            echo "ðŸ›  Running command: mvn clean install"
            mvn clean install
          else
            echo "ðŸ›  Running command: mvn clean install -pl ${{ inputs.artifact_id }} -am"
            mvn clean install -pl ${{ inputs.artifact_id }} -am
          fi

      - name: Deploy
        run: |
          echo "ðŸš€ Deploying artifact: '${{ inputs.artifact_id }}'"