name: Central Maven Build & Deploy

on:
  workflow_call:
    inputs:
      artifact_id:
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          if [ "${{ inputs.artifact_id }}" = "all" ]; then
            mvn clean install
          else
            mvn clean install -pl ${{ inputs.artifact_id }} -am
          fi

      - name: Deploy
        run: |
          echo "ðŸš€ Deploying ${{ inputs.artifact_id }}"